---
title: Mahabharata
timezone: UTC
collections:
  authors:
    title: Authors
    output: false
  news:
    title: News
    output: true
  uploads:
    title: Uploads
    output: true
  excerpts:
    title: Excerpts
    output: true
defaults:
- scope:
    path: ''
    type: news
  values:
    layout: post
    permalink: "/news/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: authors
  values:
    Name:
      first: 
      last: 
permalink: pretty
